title: Boris Shminke
email: boris@shminke.ml
description: Boris Shminke, Université Côte d'Azur, CNRS, LJAD, France
baseurl: ""
url: "https://boris.shminke.ml"
linkedin_username: inpefess
github_username:  inpefess
theme: minima
