title: Boris Shminke
email: boris@shminke.com
description: Boris Shminke, Machine Learning and Data consultant, France
baseurl: ""
url: "https://boris.shminke.com"
linkedin_username: inpefess
github_username:  inpefess
theme: minima
